new scripts

diff --git a/bin/gp b/bin/gp
--- a/bin/gp
+++ b/bin/gp
@@ -1,2 +1,7 @@
 #!/bin/bash
+CURRENT_BRANCH=$(git branch | grep \* | cut -d ' ' -f2)
+if [ "$CURRENT_BRANCH" = "master" ] || [ "$CURRENT_BRANCH" = "develop" ]; then
+    echo "ERROR: Current branch is $CURRENT_BRANCH"
+    exit 1
+fi
 git push "$@"
